version: '3.8'

services:
  back_end:
    build: .
    container_name: api-pag
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db 
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_DATABASE=nest-crud
    depends_on:
      - db 
    
  db:
    image: postgres:13
    container_name: postgres-pag
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nest-crud
    ports:
      - '5433:5432'
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: